# This file created by conda-build 3.7.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/openssl-1.0.2o-on-linux_64, last modified Tue Mar 27 14:42:22 2018
# ------------------------------------------------

package:
    name: openssl
    version: 1.0.2o
source:
    fn: openssl-1.0.2o.tar.gz
    patches:
        - 0001-win32-Fix-yasm-compatibility.patch
    sha256: ec3f5c9714ba0fd45cb4e087301eb1336c317e0d20b575a125050470e8089e4d
    url: http://www.openssl.org/source/openssl-1.0.2o.tar.gz
build:
    has_prefix_files:
        - bin/c_rehash
        - include/openssl/opensslconf.h
        - lib/pkgconfig/libcrypto.pc
        - lib/pkgconfig/libssl.pc
        - lib/pkgconfig/openssl.pc
    no_link: lib/libcrypto.so.1.0.0
    number: '0'
    run_exports:
        - openssl >=1.0.2o,<1.0.3a
    string: h20670df_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - make 4.2.1 h3d8f0fa_0
        - perl 5.26.0 hae598fd_0
    run:
        - ca-certificates
        - libgcc-ng >=7.2.0
test:
    commands:
        - touch checksum.txt
        - openssl sha256 checksum.txt
about:
    dev_url: https://github.com/openssl/openssl
    doc_url: https://www.openssl.org/docs/man1.0.2/
    home: http://www.openssl.org/
    license: OpenSSL
    license_family: Apache
    license_file: LICENSE
    summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
