# Generated by Django 2.1.4 on 2018-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100)),
                ('file_loc', models.CharField(max_length=100)),
                ('parsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
