# Generated by Django 2.1.4 on 2018-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logrecord',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fileid', models.CharField(default=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=100)),
                ('file_loc', models.CharField(max_length=100)),
                ('parsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
